### ISSUE TITLE
[autonity] Support Elastic IP

### ISSUE THREAD

**Issue by eastata** [clearmatics/charts-ose#104]
As a user (participant or validator)
I must control public IP for node
So that add support `Elastic IP` for `p2p` `LoadBalancer`

### Acceptance criteria
- IPv4 should be static
- IPv4 should not be loosed if `LB` or `chart` deleted and deployed again 

### TODO
- [x] Support AWS NodePort
- [x] Support GCP
- [x] write manual for GCP  
- [x] write manual for AWS EKS

**Comment by eastata** [comment]
https://docs.aws.amazon.com/eks/latest/userguide/load-balancing.html
