### ISSUE TITLE
[autonity] Support join Node to existent network 

### ISSUE THREAD

**Issue by eastata** [clearmatics/charts-ose#106]
As a Full Node operator
I want to join `existent` network
So that support it by `autonity` chart and add workshop

### Acceptance criteria
- [x] Private keys should not be shared to other envs
- [x] Docker images should afford to do it without k8s with manual setup for other platforms 
- [x] Write workshop

### TODO
- [x] Add export `genesis.json` with resolved `enodes` for operator
- [x] write workshop
  - [x] export genesis
  - [x] use new node to contract 
    - [x] send money to `Governance Operator` account
    - [x] craft `tx` to call governance smart-contract
    - [x] sent `tx`
- [x] test 
- [x] Release `autonity-0.0.5`

Blockers 
* [x] https://github.com/clearmatics/core/issues/322 (workaround https://github.com/clearmatics/governance-operator)
* [x] https://github.com/clearmatics/autonity/issues/320

**Comment by eastata** [comment]
Export `genesis` to `yaml`
```
kubectl -n val-1 get configmaps genesis -o 'go-template={{index .data "genesis.json"}}' |yq r -
```

**Comment by eastata** [comment]
https://github.com/clearmatics/governance-operator

**Comment by eastata** [comment]
Get Autonity Contract address
```
curl -X POST -H "Content-Type: application/json" --data '{"jsonrpc":"2.0","method":"tendermint_getContractAddress","params":[],"id":1}' http://localhost:8545
```

**Comment by eastata** [comment]
Generate eth keys to stdout
```
docker run --rm clearmatics/eth-keys-generator
```
