### ISSUE TITLE
[autonity-demo] Update grafana dashboard

### ISSUE THREAD

**Issue by eastata** [clearmatics/charts-ose#127]
As a user
I want to see new `tendermint` metrics https://github.com/clearmatics/autonity/issues/264
So that

### Acceptance criteria
-
-
-

### Related issues
-
-
-

### TODO
- [ ] build docker img for autonity release
- [ ] Deploy and create dashboard
- [ ] autonity-demo release with new dashboard

**Comment by yazzaoui** [comment]
Would be nice to have `GF_PANELS_DISABLE_SANITIZE_HTML=true`
https://github.com/grafana/grafana/blob/master/CHANGELOG.md#breaking-changes-4

so we can put javascript and do fancy stuff

**Comment by eastata** [comment]
Closed by migration to influxDB
