### ISSUE TITLE
Testnet Metrics and Logging

### ISSUE THREAD

**Issue by p1747150** [clearmatics/charts-ose#181]
Deploy new instances of metrics and logging for the Testnet network utilising the existing gke0 metrics/logging cluster and resources.

### Tasks
- Create repo for Testnet metrics (InfluxDB + grafana) -> autonity-pub-testnet-metrics
- Create repo for Testnet logging (fluentd + Elasticsearch + kibana) -> autonity-pub-testnet-logs
- Create new separate InfluxDB instance for Testnet
- Purchase SSL certificate for https://metrics.testnet.autonity.io/

### Acceptance criteria
- [ ] Grafana dashboard will be running on https://metrics.testnet.autonity.io/ for metrics
- [ ] Integrated alerting from grafana dashboard to Slack and Freshservice
- [ ] Kibana dashboard will be running for https://logs.testnet.autonity.io/ logging
