### ISSUE TITLE
CI for `autonity-network`

### ISSUE THREAD

**Issue by eastata** [clearmatics/charts-ose#3]
# Requirements

* anybody should have possibilities to sent PR
* untrusted PR should not affect our test cluster
* deploy to the repo should be after test and approve
* master should has latest version of each charts
* should has garanty that latest chart in repo - tested and approved because it will default for prod

# Workflow

![charts-ose](https://user-images.githubusercontent.com/45335213/59100100-f7bda000-891c-11e9-84a9-19da7cc09f1a.png)

# Subtasks
- [x] Create S3 bucket
- [x] Move DNS zone `charts-ose.clearmatics.com` to Route 53
- [x] Request ssl certificate
- [x] Setup CloudFront to handle traffic 
- [x] Implement deploy scripts based on https://github.com/helm/charts/blob/master/test/repo-sync.sh  (Use `AWS S3`)
- [x] Make repo public available
- [x] Write TravisCI config (releases based on tags)
