### ISSUE TITLE
Switch TravisCI from env vars to encrypted variables

### ISSUE THREAD

**Issue by eastata** [clearmatics/charts-ose#41]
As a community user
I want sent `PR` from `fork` and test it safely

### So that:
* Switch TravisCI from `env vars` to [encrypted variables](https://docs.travis-ci.com/user/encryption-keys/)
* Change workflow to receive and test external PR
* Change `CONTRIBUTION.md`

### Acceptance criteria
- Anybody should be available to sent PR
- CI should not run in test environment code that was not approved 
- Workflow should afford test and build charts after approve

### TODO
* [x] Switch TravisCI from env vars to encrypted variables
* [ ] Test from fork
* [ ] Change release flow and test it
* [ ] Describe new flow in `contributors.md`

### Related issues
- Issue #10 
- Issue #20 

> Travis CI makes encrypted variables and data available only to pull requests coming from the same repository
