### ISSUE TITLE
[autonity-network] Update autonity to v0.1.6

### ISSUE THREAD

**Issue by eastata** [clearmatics/charts-ose#66]
As a user
I want
So that

### Acceptance criteria
-
-
-

### Related issues
-
-
-

### TODO
- [x] Build autonity v0.1.6
- [x] Update `autonity-init`
- [x] Release `autonity-network` v0.3.7
- [x] Release `autonity-demo`
