### ISSUE TITLE
[autonity-network] add NetworkID option

### ISSUE THREAD

**Issue by eastata** [clearmatics/charts-ose#78]
As a user 
I want to customise `NetworkID`
So that add it to chart

### Acceptance criteria
- Chose default `network ID` (should not cross with another networks)
- enable flag `autonity .. --networkid ..` only in executing step

### TODO
- [x] Provide id as values for [autonity-network]
- [x] Provide id values for [autonity-demo]
- [ ] Deploy to PlatformX

### Additional info
```
--networkid  (integer, 1=Frontier, 2=Morden (disused), 3=Ropsten, 4=Rinkeby) (default: 1)
```
https://ethereum.stackexchange.com/questions/17051/how-to-select-a-network-id-or-is-there-a-list-of-network-ids#17101

**Comment by eastata** [comment]
Is `NetworkID` saved in LevelDB ? 
Can I change it after genesis block was generated?

**Comment by yazzaoui** [comment]
> Is `NetworkID` saved in LevelDB ?
No
> Can I change it after genesis block was generated?
Yes
