### ISSUE TITLE
[autonity-network] Genesis file generation update with Autonity v0.2.0

### ISSUE THREAD

**Issue by yazzaoui** [clearmatics/charts-ose#81]
As a user
I want the Autonity network chart to take into account changes in the genesis file with the upcoming Autonity v0.2.0-rc release.
So that the network can deploy.

### Context

Autonity 0.2.0 will contains basic network economics features, in a nutshell, it will introduce the concept of:
- _Autonity Contract_ : Soma and Glienicke contracts are now depreciated, all permissioning features are handled by a single contract.
- _Stake Token_ : stake-holders of the network are now entitled to receive a share of all transaction fees automatically pro-rata their stake. Validators are stakeholder.  
-  _minimum gas price_ : transactions with less than a certain gas price amount will get rejected. This amount can be retrieved by querying the Autonity Contract.
- _Operator account_ : Some exported  _Autonity Contract_ functions are restricted to the operator account only, notably adding and removing permissioned participants, validators or modifying the minimum gas price.

### Acceptance criteria
- Autonity v0.2.0-rc can deploy (not yet ready).

### Ressources:
https://github.com/clearmatics/autonity/wiki/Genesis-File-Configuration

### TODO
- [x] #86 [autonity 0.2.0] Refactor keys generation level
- [x] #87 [autonity 0.2.0] Refactor genesis generation level
- [x] [autonity 0.2.0] Refactor deployment/services/configmap names if need
