### ISSUE TITLE
[autonity 0.2.0] Refactor genesis generation level

### ISSUE THREAD

**Issue by eastata** [clearmatics/charts-ose#87]
Root issue #81 

### TODO
- [x]  rewrite [ibft-genesis-configurator](https://github.com/clearmatics/ibft-genesis-configurator)
  - [x] add `legacy-genesis` option
  - [x] clone and rewrite `patch_genesis()` for new genesis
  - [x] add `governanceOperator` keys load
  - [x] add `treasuryOperator` keys load
  - [x] add option `stake`
  - [x] add option `balance`
- [x] update README
- [x] modify `autonity-network` chart
